name: Setup
description: Checkout, install pnpm + Node, and install dependencies

inputs:
  fetch-depth:
    description: Number of commits to fetch (0 for full history)
    required: false
    default: "0"
  ref:
    description: Git ref to checkout
    required: false
    default: ""
  registry-url:
    description: npm registry URL (only needed for publish jobs)
    required: false
    default: ""

runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: ${{ inputs.fetch-depth }}
        ref: ${{ inputs.ref || github.ref }}

    - name: Setup pnpm
      uses: pnpm/action-setup@v4

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: 24
        registry-url: ${{ inputs.registry-url }}
        cache: pnpm

    - name: Install dependencies
      run: pnpm install --frozen-lockfile
      shell: bash
